#use_frameworks!

target 'FZNetworking_Example' do
  pod 'FZNetworking', :path => '../'
  pod 'AFNetworking', '~> 3.1.0'

  target 'FZNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
